#--------------------------------------------------------------------------------------------
# Dockerfile for Apache Spark 3.5.3 with S3A Support and custom Gluten JARs
#--------------------------------------------------------------------------------------------

# Use the official Spark base image with Java 17 and Python 3
FROM public.ecr.aws/data-on-eks/spark:3.5.3-scala2.12-java17-python3-ubuntu-s3table0.1.3-iceberg1.6.1

# Arguments for version control
ARG HADOOP_VERSION=3.4.1
ARG AWS_SDK_VERSION=2.29.0
ARG SPARK_UID=185
ARG SPARK_VERSION=3.5
ARG GLUTEN_VERSION=1.5.0
ARG TARGETARCH

# Set environment variables
ENV SPARK_HOME=/opt/spark
ENV GLUTEN_HOME=/opt/gluten

# Set up as root to install dependencies and tools
USER root

# Remove any old Hadoop libraries
RUN rm -f ${SPARK_HOME}/jars/hadoop-client-* && \
    rm -f ${SPARK_HOME}/jars/hadoop-yarn-server-web-proxy-*.jar

# Add Hadoop AWS connector and AWS SDK for S3A support, along with hadoop-common dependencies
RUN cd ${SPARK_HOME}/jars && \
    wget https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/${HADOOP_VERSION}/hadoop-aws-${HADOOP_VERSION}.jar && \
    wget https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-client-api/${HADOOP_VERSION}/hadoop-client-api-${HADOOP_VERSION}.jar && \
    wget https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-client-runtime/${HADOOP_VERSION}/hadoop-client-runtime-${HADOOP_VERSION}.jar && \
    wget https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-common/${HADOOP_VERSION}/hadoop-common-${HADOOP_VERSION}.jar && \
    wget https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-yarn-server-web-proxy/${HADOOP_VERSION}/hadoop-yarn-server-web-proxy-${HADOOP_VERSION}.jar && \
    wget https://repo1.maven.org/maven2/software/amazon/awssdk/bundle/${AWS_SDK_VERSION}/bundle-${AWS_SDK_VERSION}.jar

# Create Gluten directory
RUN mkdir -p ${GLUTEN_HOME}

# Copy the Gluten JAR files (now from build context)
COPY --chmod=644 gluten-velox-bundle-spark3.5_2.12-linux_amd64-1.5.0-SNAPSHOT-java11.jar ${GLUTEN_HOME}/
COPY --chmod=644 gluten-velox-bundle-spark3.5_2.12-linux_aarch64-1.5.0-SNAPSHOT.jar ${GLUTEN_HOME}/

# Copy the appropriate JAR to Spark jars directory based on architecture
RUN if [ "$TARGETARCH" = "amd64" ]; then \
        cp ${GLUTEN_HOME}/gluten-velox-bundle-spark3.5_2.12-linux_amd64-1.5.0-SNAPSHOT-java11.jar  ${SPARK_HOME}/jars/gluten-velox.jar; \
    elif [ "$TARGETARCH" = "arm64" ]; then \
        cp ${GLUTEN_HOME}/gluten-velox-bundle-spark3.5_2.12-linux_aarch64-1.5.0-SNAPSHOT.jar ${SPARK_HOME}/jars/gluten-velox.jar; \
    fi

# Set working directory
WORKDIR ${SPARK_HOME}

# Switch to non-root user
USER ${SPARK_UID}
